name: Build W5500 EVB Pico2
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Show repo structure
        run: find ports/rp2/boards -maxdepth 1 -type d | sort
